name: Linux

on:
  push:
    branches:
      - master
      - 4.x
  pull_request:

jobs:
  ubuntu-latest:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-versions: [ '7.2', '7.3', '7.4', '8.1' ]
        coverage: [none]
        include:
          -   php-versions: '8.0'
              coverage: xdebug
      fail-fast: false

    name: PHP ${{ matrix.php-versions }} on ubuntu-latest

    steps:
      -   name: PHP
          uses: shivammathur/setup-php@v2
          with:
            php-version: ${{ matrix.php-versions }}
            coverage: ${{ matrix.coverage }}

      -   name: Checkout
          uses: actions/checkout@v2

      -   name: Configure
          run: cp resources/configurations/ci/.github.php.dist .atoum.php

      -   name: Run
          continue-on-error: ${{ matrix.experimental }}
          run: bin/atoum --enable-branch-and-path-coverage
